'''Green fractals constants'''
RANDOM_SEED = 1
FRAME_SIZE = 1024
ITERATIONS = 1_000
POINTS = 10_000
ESCAPE_RADIUS = 20
REGIONS_DIM = 100
PRODUCE_IMAGES = True
COMPLEX_RANGE = 2.0
RATIO = FRAME_SIZE / (2 * COMPLEX_RANGE)
